version: "3.8"

services:
  bot:
    build: .
    container_name: diszone_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
    volumes:
      - ./bot_data:/app/bot_data
      - ./plazas.db:/app/plazas.db

